### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by jasonw4331** [jasonwynn10/FakeAdmin#1]
- [ ] Entity AI
  - [ ] Chat scripted responses
    - [x] Separate lang file from config
    - [ ] Fill in defaults
  - [ ] Movement AI @sandertv
  - [ ] Inventory interactions
  - [ ] World/Block interactions
  - [ ] Player interactions
    - [ ] pvp
      - [ ] melee
      - [ ] shooting bows
    - [ ] minigame modes
- [x] Ability to use commands when the need arises
  - [x] Scripted command use
  - [ ] Smart command use
- [ ] Bypass server player login system (may not have to)

**Comment by Sandertv** [comment]
Yessir :D

**Comment by Sandertv** [comment]
What exactly should the fake admin do? I assume flying around, looking at players etc, but is there any other requirement, or should I just use my imagination?

I just got an hilarious idea. What if we'd add some kind of chat defending system, where if you say a bad word the fake admin teleports to you and starts attacking you? :P

**Comment by jasonw4331** [comment]
I think it would be good to have the admin tp near the player it's talking to. It would also be cool if it could simulate having hacks using invisible effects. The player should be able to complete requests too such as being able to place and break blocks where requested.

**Comment by TheDiamondYT1** [comment]
If you restructure the chat-scripts file to allow arrays then i'll contribute. I'd like to implement random responses

**Comment by jasonw4331** [comment]
@TheDiamondYT1 I already did, but it cycles through each within the array rather than using a singular response. Random responses might need a separate file.

**Comment by Sandertv** [comment]
@jasonwynn10 do we really need to use specter? It makes the code a whole lot more complicated, and we could mirror it without having to log in and stuff. We can even make it show up in the player list without it.

**Comment by jasonw4331** [comment]
@Sandertv If you want to have the plugin work another way, feel free to make the needed changes. You can do the entity things,  I just want to make sure it can interact with Players as another and interact with the world as a player.
